---

- name: Ensure the Ansible install directory exists
  file:
    path: "{{ controller_ansible_install_dir }}"
    state: directory

- name: Ensure Ansible is installed in a virtual environment
  pip:
    name: ansible
    version: "{{ controller_ansible_version }}"
    state: present
    virtualenv: "{{ controller_ansible_install_dir }}/ansible-{{ controller_ansible_version }}"
    virtualenv_command: "{{ controller_python3_path }} -m venv"

- name: Ensure the current release is symlinked in the install directory
  file:
    src: "{{ controller_ansible_install_dir }}/ansible-{{ controller_ansible_version }}"
    dest: "{{ controller_ansible_install_dir }}/{{ controller_ansible_current_dirname }}"
    state: link

- name: Ensure venv wrapper exists in virtualenv bin directory
  template:
    src: venv.sh.j2
    dest: "{{ controller_ansible_install_dir }}/ansible-{{ controller_ansible_version }}/bin/venv"
    mode: 0755

- name: Ensure Ansible configuration directory exists
  file:
    path: "{{ controller_ansible_config_path | dirname }}"
    state: directory

- name: Ensure Ansible inventory directory exists
  file:
    path: "{{ controller_ansible_inventory_path | dirname }}"
    state: directory

- name: Ensure Ansible roles directory exists
  file:
    path: "{{ controller_ansible_roles_dir }}"
    state: directory

- name: Ensure Ansible projects directory exists
  file:
    path: "{{ controller_ansible_projects_dir }}"
    state: directory
