---

- import_tasks: pre-checks-os.yml

- include_tasks: "{{ ansible_os_family | lower }}/install-os-dependencies.yml"
  when: controller_install_os_dependencies is defined
        and controller_install_os_dependencies

- import_tasks: pre-checks-environment.yml

- import_tasks: install-ansible.yml

- import_tasks: configure-ansible.yml

- import_tasks: install-roles.yml
  when: controller_ansible_galaxy_roles is defined
        and controller_ansible_galaxy_roles | length > 1

- import_tasks: post-checks-environment.yml
