---

- name: Check to see if the Ansible version directory exists
  stat:
    path: "{{ controller_ansible_install_dir }}/{{ controller_ansible_venv_name }}-{{ controller_ansible_venv_suffix }}"
  register: controller_check_ansible_version_dir

- name: Fail if the Ansible version directory doesn't exist
  fail:
    msg: "{{ controller_ansible_install_dir }}/{{ controller_ansible_venv_name }}-{{ controller_ansible_venv_suffix }} is missing after play."
  when: not controller_check_ansible_version_dir.stat.exists

- name: Ensure venv target variable is set
  set_fact:
    controller_ansible_venv_target: "{{ controller_ansible_install_dir }}/{{ controller_ansible_venv_name }}-{{ controller_ansible_venv_suffix }}"

- name: Check to see if the Ansible current symlink exists
  stat:
    path: "{{ controller_ansible_install_dir }}/{{ controller_ansible_venv_name }}"
  register: controller_check_ansible_symlink_dir

- name: Fail if the Ansible symlink directory doesn't exist
  fail:
    msg: "{{ controller_ansible_install_dir }}/{{ controller_ansible_venv_name }} symlink not correct after play."
  when: not controller_check_ansible_symlink_dir.stat.exists
        or not controller_check_ansible_symlink_dir.stat.islnk
        or controller_check_ansible_symlink_dir.stat.lnk_target != (controller_ansible_venv_target)

- name: Check to see if the Ansible version directory is a virtualenv
  stat:
    path: "{{ controller_ansible_install_dir }}/{{ controller_ansible_venv_name }}/bin/activate"
  register: controller_check_ansible_virtualenv_dir

- name: Fail if the Ansible virtualenv directory doesn't exist
  fail:
    msg: "{{ controller_ansible_install_dir }}/{{ controller_ansible_venv_name }}/bin/activate not found after play."
  when: not controller_check_ansible_virtualenv_dir.stat.exists
        or not controller_check_ansible_virtualenv_dir.stat.isreg

- name: Check to see if the Ansible config file exists
  stat:
    path: "{{ controller_ansible_config_path }}"
  register: controller_check_ansible_config_file

- name: Fail if the Ansible config file doesn't exist
  fail:
    msg: "The specified ansible config file does not exists: {{ controller_ansible_config_path }}"
  when: not controller_check_ansible_config_file.stat.exists
        or not controller_check_ansible_config_file.stat.isreg

- name: Check to see if the Ansible inventory file exists
  stat:
    path: "{{ controller_ansible_inventory_path }}"
  register: controller_check_ansible_inventory_file

- name: Fail if the Ansible inventory file doesn't exist
  fail:
    msg: "The specified ansible inventory file does not exists: {{ controller_ansible_inventory_path }}"
  when: not controller_check_ansible_inventory_file.stat.exists
        or not controller_check_ansible_inventory_file.stat.isreg

- name: Check to see if the Ansible role directory exists
  stat:
    path: "{{ controller_ansible_roles_dir }}"
  register: controller_check_ansible_roles_dir

- name: Fail if the Ansible role directory doesn't exist
  fail:
    msg: "The specified ansible role directory does not exists: {{ controller_ansible_roles_dir }}"
  when: not controller_check_ansible_roles_dir.stat.exists
        or not controller_check_ansible_roles_dir.stat.isdir

- name: Check to see if the Ansible project directory exists
  stat:
    path: "{{ controller_ansible_projects_dir }}"
  register: controller_check_ansible_projects_dir

- name: Fail if the Ansible project directory doesn't exist
  fail:
    msg: "The specified ansible project directory does not exists: {{ controller_ansible_projects_dir }}"
  when: not controller_check_ansible_projects_dir.stat.exists
        or not controller_check_ansible_projects_dir.stat.isdir
