---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: controller
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
provisioner:
  name: ansible
  options:
    verbose: true
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-${USER}/tmp
  lint:
    name: ansible-lint
  playbooks:
    prepare: ${MOLECULE_PREPARE_PLAYBOOK:-prepare.yml}
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
verifier:
  name: testinfra
  lint:
    name: flake8
