---
- name: Converge
  hosts: all
  become: true
  vars:
    controller_install_os_dependencies: true
    controller_ansible_install_dir: /opt/ansible/bin
    controller_ansible_config_path: /etc/ansible/ansible.cfg
    controller_ansible_inventory_path: /etc/ansible/hosts
    controller_ansible_project_dir: /opt/ansible/projects
    controller_ansible_current_dirname: current
  roles:
    - role: xanmanning.controller
