---
- name: Converge
  hosts: all
  become: true
  vars:
    controller_install_os_dependencies: true
    controller_ansible_install_dir: /opt/ansible/bin
    controller_ansible_config_path: /etc/ansible/ansible.cfg
    controller_ansible_inventory_path: /etc/ansible/hosts
    controller_ansible_projects_dir: /opt/ansible/projects
    controller_ansible_roles_dir: /opt/ansible/roles
    controller_ansible_bin_dir: /usr/bin
    controller_ansible_venv_name: current
    controller_ansible_support_packages:
      - azure
    controller_ansible_galaxy_roles:
      - src: geerlingguy.swap
      - name: awx
        src: geerlingguy.awx
      - name: git
        src: https://github.com/geerlingguy/ansible-role-git
        scm: git
        version: 2.1.0
    controller_ansible_projects:
      - name: mac-dev-workstation
        repo: https://github.com/geerlingguy/mac-dev-playbook
      - repo: git://github.com/geerlingguy/awx-container.git
        version: 1.0.7
        update_repo: false
    controller_ansible_projects_install_roles: true
  roles:
    - role: xanmanning.controller
