---

- name: Prepare containers for local-user install testing
  hosts: all
  become: true
  tasks:
    - name: Ensure a user group exists
      group:
        name: user
        state: present

    - name: Ensure a normal user exists
      user:
        name: ansibleuser
        group: user
        state: present

    - name: Ensure prerequisite packages are installed
      package:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
