---

- name: Prepare containers for global install testing
  hosts: all
  become: true
  tasks:
    - name: Ensure prerequisite git packages are installed
      package:
        name: git
        state: present
