---

- name: Ensure Python 3 and Python Pip is installed
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Ensure git is installed
  apt:
    name: git
    state: present
